project_id = "pugtpiijinkulpbnbgji"
[functions.get-weekly-threads]
enabled = true
verify_jwt = true
import_map = "./functions/get-weekly-threads/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-weekly-threads/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-weekly-threads/*.html" ]

[functions.get-client-insights]
enabled = true
verify_jwt = true
import_map = "./functions/get-client-insights/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-client-insights/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-client-insights/*.html" ]

[functions.get-email-thread]
enabled = true
verify_jwt = true
import_map = "./functions/get-email-thread/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-email-thread/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-email-thread/*.html" ]

[functions.update-communication-summary]
enabled = true
verify_jwt = true
import_map = "./functions/update-communication-summary/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-communication-summary/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-communication-summary/*.html" ]
